<h2>Sign up</h2>

<?php echo $this->tag->form("signup/register"); ?>

    <p>
        <label for="login">login</label>
        <?php echo $this->tag->textField("login"); ?>
    </p>

    <p>
        <label for="password">password</label>
        <?php echo $this->tag->textField("password"); ?>
    </p>

   <p>
        <label for="email">email</label>
        <?php echo $this->tag->textField("email"); ?>
    </p>
   
    <p>
        <?php echo $this->tag->submitButton("Register"); ?>
    </p>

				<?php
echo PHP_EOL;
echo PHP_EOL;
echo $this->tag->linkTo(['index','Sign In Here!', 'class' => 'btn btn-primary']);?>
